CREATE TABLE NGUOIDUNG (
    MAND VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR(100) NOT NULL,
    GIOITINH CHAR(1) CHECK(GIOITINH IN ('M', 'F')),
    NGAYSINH DATE,
    EMAIL VARCHAR2(100),
    MATKHAU VARCHAR2(20),
    VAITRO VARCHAR2(2) CHECK(VAITRO IN ('KH', 'NV', 'QT'))
);


CREATE TABLE SACH (
    MASACH VARCHAR2(20) PRIMARY KEY,
    TIEUDE VARCHAR2(200) NOT NULL,
    TACGIA VARCHAR2(100),
    MOTA CLOB,
    THELOAI VARCHAR2(100),
    GIA NUMBER(10, 2) CHECK (GIA >= 0),
    NHAPHATHANH VARCHAR2(100),
    NGAYPHATHANH DATE,
    NGONNGU VARCHAR2(50),
    DOTUOI VARCHAR2(20),
    SOTRANG NUMBER CHECK (SOTRANG > 0),
    KICHTHUOC VARCHAR2(50),
    SOLUONG NUMBER CHECK (SOLUONG >= 0)
);


CREATE TABLE DIACHI (
    MADCHI VARCHAR2(20) PRIMARY KEY,
    MAKH VARCHAR2(20),
    SONHA VARCHAR2(100),
    DUONG VARCHAR2(100),
    KHUPHO VARCHAR2(100),
    QUAN VARCHAR2(100),
    THANHPHO VARCHAR2(100)
);


CREATE TABLE DONDATHANG (
    MADDH VARCHAR2(20) PRIMARY KEY,
    MAKH VARCHAR2(20),
    NGAYDH DATE,
    NGAYGIAO DATE,
    TONGTIEN NUMBER(12, 2) CHECK (TONGTIEN >= 0)
);


CREATE TABLE CHITIETDDH (
    MACTDDH VARCHAR2(20) PRIMARY KEY,
    MADDH VARCHAR2(20),
    MASACH VARCHAR2(20),
    MAGG VARCHAR2(20) NULL,
    SOLUONG NUMBER CHECK (SOLUONG > 0),
    DONGIA NUMBER(12, 2) CHECK (DONGIA >= 0),
    THANHTIEN NUMBER(12, 2) CHECK (THANHTIEN >= 0)
);


CREATE TABLE GIOHANG (
    MAGH VARCHAR2(20) PRIMARY KEY,
    MAND VARCHAR2(20)
);


CREATE TABLE CHITIETGIOHANG (
    MACTGH VARCHAR2(20) PRIMARY KEY,
    MAGH VARCHAR2(20),
    MASACH VARCHAR2(20),
    SOLUONG NUMBER CHECK (SOLUONG > 0),
    DONGIA NUMBER(12, 2) CHECK (DONGIA >= 0)
);


CREATE TABLE HOADON(
    MAHD VARCHAR2(20) PRIMARY KEY,
    MAKH VARCHAR2(20),
    MADDH VARCHAR2(20),
    MANV VARCHAR2(20),
    NGAYLAP DATE,
    TONGTHANHTIEN NUMBER(12,2) CHECK (TONGTHANHTIEN >= 0)
);


CREATE TABLE CHITIETHD (
    MACTHD VARCHAR2(20) PRIMARY KEY,
    MAHD VARCHAR2(20),
    MASACH VARCHAR2(20),
    SOLUONG NUMBER CHECK (SOLUONG > 0),
    DONGIA NUMBER(12, 2) CHECK (DONGIA >= 0),
    THANHTIEN NUMBER(12, 2) CHECK (THANHTIEN >= 0)
);


CREATE TABLE PHIEUGIAMGIA (
    MAGG VARCHAR2(20) PRIMARY KEY,
    GIATRI NUMBER(12, 2) CHECK (GIATRI >= 0),
    NGAYHETHAN DATE,
    SOLUONG NUMBER CHECK (SOLUONG >= 0)
);



---RÀNG BUỘC KHÓA NGOẠI
ALTER TABLE DIACHI ADD CONSTRAINT FK_DIACHI_NGUOIDUNG FOREIGN KEY (MAKH) REFERENCES NGUOIDUNG(MAND);
ALTER TABLE DONDATHANG ADD CONSTRAINT FK_DONDATHANG_NGUOIDUNG FOREIGN KEY (MAKH) REFERENCES NGUOIDUNG(MAND);
ALTER TABLE CHITIETDDH ADD CONSTRAINT FK_CHITIETDDH_DONDATHANG FOREIGN KEY (MADDH) REFERENCES DONDATHANG(MADDH);
ALTER TABLE CHITIETDDH ADD CONSTRAINT FK_CHITIETDDH_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH);
ALTER TABLE CHITIETDDH ADD CONSTRAINT FK_CHITIETDDH_PHIEUGIAMGIA FOREIGN KEY (MAGG) REFERENCES PHIEUGIAMGIA(MAGG);
ALTER TABLE GIOHANG ADD CONSTRAINT FK_GIOHANG_NGUOIDUNG FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND);
ALTER TABLE CHITIETGIOHANG ADD CONSTRAINT FK_CHITIETGIOHANG_GIOHANG FOREIGN KEY (MAGH) REFERENCES GIOHANG(MAGH);
ALTER TABLE CHITIETGIOHANG ADD CONSTRAINT FK_CHITIETGIOHANG_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH);
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES NGUOIDUNG(MAND);
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MANV) REFERENCES NGUOIDUNG(MAND);
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_DONDATHANG FOREIGN KEY (MADDH) REFERENCES DONDATHANG(MADDH);
ALTER TABLE CHITIETHD ADD CONSTRAINT FK_CHITIETHD_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD);
ALTER TABLE CHITIETHD ADD CONSTRAINT FK_CHITIETHD_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH);




