CREATE TABLE BOOK (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TITLE VARCHAR2(255),
  AUTHOR VARCHAR2(255),
  DESCRIPTION VARCHAR2(1000),
  CATEGORY VARCHAR2(100),
  PRICE NUMBER(10,2),
  PUBLISHER VARCHAR2(255),
  PUBLICATIONDATE DATE,
  LANGUAGE VARCHAR2(50),
  READINGAGE NUMBER,
  PAGES NUMBER,
  DIMENSION VARCHAR2(50)
);

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('Financial Feminist', 'Brianna Miller', 'A groundbreaking exploration of feminist economics in modern finance', 'Finance', 35.00, 'EmpowerPress', TO_DATE('2019-06-15','YYYY-MM-DD'), 'English', 18, 320, '6x9');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('No More Police', 'James Carter', 'A provocative critique of law enforcement practices in contemporary society', 'Sociology', 28.50, 'JusticeHouse', TO_DATE('2018-11-10','YYYY-MM-DD'), 'English', 16, 280, '6x9');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('I''m Glad My Mom Died', 'Lisa Andrews', 'A memoir about loss, love, and the complicated legacy of a mother', 'Memoir', 22.99, 'Heartfelt Publishing', TO_DATE('2020-03-05','YYYY-MM-DD'), 'English', 17, 250, '6x9');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('Nona the Ninth', 'Rachel Summers', 'An epic fantasy tale of magic, mystery, and ancient legacies', 'Fantasy', 30.00, 'MythicBooks', TO_DATE('2021-09-21','YYYY-MM-DD'), 'English', 14, 410, '6x9');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('1984', 'George Orwell', 'A dystopian novel about totalitarian regimes and surveillance', 'Fiction', 15.99, 'Secker and Warburg', TO_DATE('1949-06-08','YYYY-MM-DD'), 'English', 16, 328, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('Animal Farm', 'George Orwell', 'An allegorical novella reflecting events leading up to the Russian Revolution', 'Political Satire', 12.99, 'Secker and Warburg', TO_DATE('1945-08-17','YYYY-MM-DD'), 'English', 16, 112, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 'A classic novel depicting the American society during the Roaring Twenties', 'Fiction', 10.99, 'Charles Scribner''s Sons', TO_DATE('1925-04-10','YYYY-MM-DD'), 'English', 15, 180, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('To Kill a Mockingbird', 'Harper Lee', 'A novel about racial injustice and the destruction of innocence', 'Fiction', 14.99, 'J.B. Lippincott and Co.', TO_DATE('1960-07-11','YYYY-MM-DD'), 'English', 12, 281, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('Pride and Prejudice', 'Jane Austen', 'A classic romance novel that also critiques the British landed gentry', 'Romance', 9.99, 'T. Egerton', TO_DATE('1813-01-28','YYYY-MM-DD'), 'English', 14, 432, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Catcher in the Rye', 'J.D. Salinger', 'A novel about teenage rebellion and alienation', 'Fiction', 13.99, 'Little, Brown and Company', TO_DATE('1951-07-16','YYYY-MM-DD'), 'English', 13, 214, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('Moby Dick', 'Herman Melville', 'An epic tale of the voyage of the whaling ship Pequod', 'Adventure', 11.99, 'Harper and Brothers', TO_DATE('1851-11-14','YYYY-MM-DD'), 'English', 18, 635, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('War and Peace', 'Leo Tolstoy', 'A historical epic that intertwines the lives of families during the Napoleonic Wars', 'Historical', 20.99, 'The Russian Messenger', TO_DATE('1869-01-01','YYYY-MM-DD'), 'Russian', 18, 1225, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Lord of the Rings', 'J.R.R. Tolkien', 'An epic high-fantasy novel set in Middle-earth', 'Fantasy', 29.99, 'Allen and Unwin', TO_DATE('1954-07-29','YYYY-MM-DD'), 'English', 12, 1216, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Hobbit', 'J.R.R. Tolkien', 'A prelude to The Lord of the Rings, detailing Bilbo Baggins'' adventure', 'Fantasy', 14.99, 'Allen and Unwin', TO_DATE('1937-09-21','YYYY-MM-DD'), 'English', 10, 310, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'The first installment of the Harry Potter series, introducing the magical world', 'Fantasy', 19.99, 'Bloomsbury', TO_DATE('1997-06-26','YYYY-MM-DD'), 'English', 8, 223, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Da Vinci Code', 'Dan Brown', 'A mystery thriller that follows symbologist Robert Langdon', 'Thriller', 16.99, 'Doubleday', TO_DATE('2003-04-03','YYYY-MM-DD'), 'English', 14, 689, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Alchemist', 'Paulo Coelho', 'A philosophical novel about following your dreams and listening to your heart', 'Fiction', 12.99, 'HarperTorch', TO_DATE('1988-04-01','YYYY-MM-DD'), 'Portuguese', 12, 197, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Kite Runner', 'Khaled Hosseini', 'A story of friendship and redemption set against the backdrop of Afghanistan', 'Fiction', 14.99, 'Riverhead Books', TO_DATE('2003-05-29','YYYY-MM-DD'), 'English', 14, 371, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Girl on the Train', 'Paula Hawkins', 'A psychological thriller about the secrets observed during a daily commute', 'Thriller', 13.99, 'Riverhead Books', TO_DATE('2015-01-13','YYYY-MM-DD'), 'English', 15, 395, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('Gone Girl', 'Gillian Flynn', 'A suspenseful thriller that explores the complexities of marriage', 'Thriller', 15.99, 'Crown', TO_DATE('2012-06-05','YYYY-MM-DD'), 'English', 16, 422, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Fault in Our Stars', 'John Green', 'A touching story about young love and the challenges of illness', 'Fiction', 12.99, 'Dutton Books', TO_DATE('2012-01-10','YYYY-MM-DD'), 'English', 12, 313, '5x8');

INSERT INTO BOOK (TITLE, AUTHOR, DESCRIPTION, CATEGORY, PRICE, PUBLISHER, PUBLICATIONDATE, LANGUAGE, READINGAGE, PAGES, DIMENSION)
VALUES ('The Chronicles of Narnia', 'C.S. Lewis', 'A classic fantasy series that transports readers to the magical world of Narnia', 'Fantasy', 25.99, 'Geoffrey Bles', TO_DATE('1950-10-16','YYYY-MM-DD'), 'English', 10, 768, '5x8');
